dataModel:
  dataSource: path1
  datasetName: test1
  dateformat: "%m-%d-%Y"
  columns:
    - key
    - date
    - new_confirmed
    - new_deceased
    - total_confirmed
    - total_deceased
  
visualization:
  type: LinearPlot
  axes:
    x:
      label: "Date"
      column: date
    y:
      label: "New Cases"
      column: new_confirmed
    z:
      label: "Country"
      column: key
  info:
    title: "COVID-19 New Cases in Europe"
    subTitle: "Spain, United Kingdm, Italy, Sweden, Netherlands, Germany"
    caption: "Source: Google Open Data"

