dataModel:
  dataSource: path1
  datasetName: abc.csv
  columns:
    - c1
    - c2
    - c3
    - c4
  
visualization:
  type: ScatterPlot
  axes:
    x:
      label: "Total Infection"
      column: total_deceased
      scale: 
        type: Log10
    y:
      label: "Total Deaths"
      column: total_confirmed
    z:
      label: "Country"
      column: new_confirmed
  info:
    title: "Infection vs Death"
    subTitle: "..."
    caption: "Source: Google Open Data"

animation:
  label: "Date: "
  transitionTime: DateS
  width: 800
  height: 500
  duration: 20
  outputName: graph.gif
  outputPath: out
  
regression:
  type: Logarithmic
  dependentValue: total_deceased
  independentValue: total_confirmed
