dataModel:
  dataSource: path1
  datasetName: abc
  dateformat: "%m-%d-%Y" # Date format in columns with the Date type
  filters: #Filtering unwanted values (in this case in key column only SE will remain)
    - key: key
      value: SE
    - key: date
      value: UK
  columns:
    - key
    - date
    - new_confirmed
    - new_deceased
    - total_confirmed
    - total_deceased
  
visualization:
  type: ScatterPlot #ScatterPlot, LinearPlot
  size: new_confirmed
  axes:
    x:
      label: "Total Infection"
      column: total_deceased
      scale: 
        type: Log #Log, Srt, date
    y:
      label: "Total Deaths"
      column: total_confirmed
      scale: 
        type: Date
        format: "%m-%d"
        breaks: "2 weeks"
    z: # Use as color value in a scatter plot
      label: "Country"
      column: new_confirmed
  info:
    title: "Infection vs Death"
    subTitle: "..."
    caption: "Source: Google Open Data"

animation:
  label: "Date: "
  transitionTime: date_d #Day->date_d, Week->date_w, Hour->date_h, Minute->date_m, Seconds->date_s will be autogenerated from every date format
  width: 800
  height: 500
  duration: 20
  outputName: graph # always save as a .gif file
  outputPath: out
  
regression:
  type: Logarithmic #Linear, Logarithmic
  dependentValue: total_deceased
  independentValue: total_confirmed
